---
kind: pipeline
type: docker
name: default
globals:
  - &docker_creds
    username:
      from_secret: docker_user
    password:
      from_secret: docker_password
steps:
  - name: prepare
    image: busybox
    commands:
      - mkdir -p /cache/${DRONE_REPO}/docker
    volumes:
      - name: cache
        path: /cache
  - name: env_prod
    image: nightfuryest/drone-plugin-secret-to-env
    settings:
      template: .deploy/.env.prod.template
      file: .env
      envs:
        - DB_USERNAME
        - DB_PASSWORD
      DB_USERNAME:
        from_secret: DEFAULT_DB_ROOT_USER
      DB_PASSWORD:
        from_secret: DEFAULT_DB_ROOT_PASSWORD
    when:
      branch:
        - production
  - name: Install PHP Packages
    image: nightfuryest/php-composer
    commands:
      - composer install
    environment:
      COMPOSER_CACHE_DIR: /composer
    volumes:
      - name: composer
        path: /composer
    when:
      branch:
        - production
  - name: Build assets
    image: node:13-alpine
    commands:
      - node -v
      - npm -v
      - yarn --version
      - yarn config set cache-folder /yarn
      - yarn install --pure-lockfile
      - yarn prod
    volumes:
      - name: yarn
        path: /yarn
    when:
      branch:
        - production
  - name: compress
    image: kramos/alpine-zip
    commands:
      - rm -rf node_modules
      - rm -rf .git
      - zip -r workspace.zip * .* -x "node_modules/*" ".git/*"
    when:
      branch:
        - production
  - name: deploy
    image: nightfuryest/drone-plugin-webpress-manager
    settings:
      domain: p16002.webpress.vn
      api_key:
        from_secret: WEBPRESS_MANAGER_PRIVATE_API_KEY
      api_secret:
        from_secret: WEBPRESS_MANAGER_PRIVATE_API_SECRET
    when:
      branch:
        - production
volumes:
  - name: cache
    host:
      path: /var/cache
  - name: docker
    host:
      path: /var/cache/${DRONE_REPO}/docker
  - name: composer
    host:
      path: /var/cache/${DRONE_REPO}/composer
  - name: yarn
    host:
      path: /var/cache/${DRONE_REPO}/yarn

trigger:
  branch:
    - production
